cp -rf ./lico_project_file/build.sh  ./sdk/project
cp -rf ./lico_project_file/BoardConfig-SPI_NAND-Buildroot-RV1106_Lico.mk ./sdk/project/cfg/BoardConfig_IPC
cp -rf ./lico_project_file/rv1106g-lico.dts ./sdk/sysdrv/source/kernel/arch/arm/boot/dts
cp -rf ./lico_project_file/rv1106-lico-ipc.dtsi ./sdk/sysdrv/source/kernel/arch/arm/boot/dts
cp -rf ./lico_project_file/lico_rv1106_uboot_defconfig ./sdk/sysdrv/source/uboot/u-boot/configs
cp -rf ./lico_project_file/lico_rv1106_linux_defconfig ./sdk/sysdrv/source/kernel/arch/arm/configs
cp -rf ./lico_project_file/lico_defconfig ./sdk/sysdrv/tools/board/buildroot
cp -rf ./lico_project_file/make_fit_uboot.sh ./sdk/sysdrv/source/uboot/u-boot/arch/arm/mach-rockchip
cp -rf ./lico_project_file/Makefile ./sdk/sysdrv