#!/bin/sh

case $1 in
        start)
                echo "start"
                chmod 777 /root/main
                /root/main
                echo "desktop run success!"
                ;;
        stop)
                echo "stop"
                ;;
        *)
                exit 1
                ;;
esac